[package]
name = "cosmic-hello"
version = "0.1.0"
edition = "2021"

[dependencies]


[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["wayland", "wgpu"]
